# Generated by Django 4.2.4 on 2023-08-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
